### ISSUE TITLE
why all test ends with segment fault

### ISSUE THREAD

**Issue by biaohanli** [tcwangshiqi-columbia/Neurify#13]
I have tried to run the tests , but no matter which parameters i tried ,it always returns segment fault or code dump.
why?My server's ram is 12GB.
thanks.

**Comment by ChristopherBrix** [comment]
Could you please specify the concrete command you're trying to execute? And are you using the `general` folder, or `dave`/`drebin`? Are you getting any output at all, before you get the segfault?

**Comment by biaohanli** [comment]
1. i used general
2. the command is ./network_test 0 models/conv.nnet
and other command is also segfault.
3. I can get some info before crash.
[IMG_2586.HEIC.pdf](https://github.com/tcwangshiqi-columbia/Neurify/files/4593907/IMG_2586.HEIC.pdf)

**Comment by ChristopherBrix** [comment]
Ok, this may very well be caused by a memory leak. I cannot reproduce the segmentation fault, but on my PC it just allocates memory until it's aborted.
Please try to [apply](https://thoughtbot.com/blog/send-a-patch-to-someone-using-git-format-patch) the following change locally:

```
From 03b19e752b4fe24d808c24f837758a511c7f56d4 Mon Sep 17 00:00:00 2001
From: Christopher Brix <Christopher.Brix@rwth-aachen.de>
Date: Thu, 7 May 2020 19:14:03 +0200
Subject: [PATCH] Fixed memory leaks

---
 general/network_test.c | 2 ++
 general/nnet.c         | 3 +++
 2 files changed, 5 insertions(+)

diff --git a/general/network_test.c b/general/network_test.c
index b9a191b..9301044 100644
--- a/general/network_test.c
+++ b/general/network_test.c
@@ -406,6 +406,8 @@ int main( int argc, char *argv[]){
         free(new_equation);
         free(equation_err);
         free(new_equation_err);
+        free(equation_conv);
+        free(equation_conv_err);
         delete_lp(lp);
 
     }
diff --git a/general/nnet.c b/general/nnet.c
index 6e05a39..49732f4 100644
--- a/general/nnet.c
+++ b/general/nnet.c
@@ -1149,6 +1149,9 @@ void sym_conv_layer(struct SymInterval *sInterval, struct NNet *nnet,
             }
         }
     }
+
+    free(new_new_equation);
+    free(new_new_equation_err);
 }
 
 
-- 
2.26.2
```

Please note that just checking image 1 took so long, I had to abort it at some point. You might want to decrease the `INF` value in `network_test.c` to get reasonable runtimes.
If you don't actually need to test convolutional networks, and simple fully connected feed forward layers are enough for you, you might want to use my PR #9. Similar optimizations would be possible for convolutions, but I didn't have time to look at them so far.

**Comment by biaohanli** [comment]
memory in my machine is 12GB
how about your machine?

**Comment by biaohanli** [comment]
@@ -1149,6 +1149,9 @@ void sym_conv_layer(struct SymInterval *sInterval, struct NNet *nnet,
             }
         }
     }
+
+    free(new_new_equation);
+    free(new_new_equation_err);
 }
and which ?
I can decide where to change.

**Comment by ChristopherBrix** [comment]
Applying the patch should be possible with `cat patch_file.txt | git am` (see https://thoughtbot.com/blog/send-a-patch-to-someone-using-git-format-patch). Anyway, it's at the end of the `for` loop in `main`, and at the end of `sym_conv_layer`.

My machine has 16GB, but I've monitored the usage using `htop` and I think it stayed at like 10GB? So it might be a tight fit, and you should make sure that no other programs are running in parallel. I'm no expert, but maybe even try to disable the whole GUI if you're using Ubuntu or something similar. Just free as much space as possible.

If you're still running into memory issues, please try smaller networks or possibly smaller `INF` sizes. (Or, try to get a machine with more RAM, but I can see why this might not be possible).
Maybe you can [define some swap space](https://opensource.com/article/18/9/swap-space-linux-systems)?

I'm sorry for the inconvenience - I am currently working on the logic for feed forward layers (see my PR). Hopefully, I'll find some time later on to improve the logic for convolutions as well, which may (or may not) decrease the memory consumption. But this probably won't happen in the next few weeks, so it may be to late for you.

**Comment by biaohanli** [comment]
I tried 16GB and it still failed...

**Comment by ChristopherBrix** [comment]
But you did try after applying the patch, right? Could you please also try to lower the `INF` value (eg. start with `1` and increase step wise until it fails). And please also try smaller networks (you may just delete intermediate layers from the `conv.nnet` file to simulate a smaller network).

If it still doesn't work, please pull my PR #9 and use it to test a feed forward network (eg. `models/mnist24.nnet`). If even that fails, it may be related to your setup. Maybe OpenBLAS isn't properly installed? Did you check that? 

To help locating the bug, please also try to run it using valgrind: `make clean; make debug && valgrind --leak-check=full --vex-guest-max-insns=25 ./network_test 0 models/conv.nnet`. Maybe that will provide additional hints.

Edit: Please also set `image_length = 1`, so you only evaluate one image.

**Comment by biaohanli** [comment]
i tried ./network_test 0 models/conv.nnet on a 64GB server
the segmentfault always appears.
lol...

**Comment by ChristopherBrix** [comment]
Ok, so it's probably not related to memory issues. But still, could you please follow all the advice I gave you? Again:
 - set `image_length = 1`
 - try `INF=1`. Does it work? If yes, increase it. When does it fail?
 - try a smaller network
 - try running it with valgrind. Post all the output
 - check out my PR and run an analysis of a feed forward network

And I want to add: 
 - run `htop` while running the analysis and monitor CPU and memory usage. What do you see? Is everything maxed out, or are there still free resources when it crashes?

As I cannot reproduce your issues right now, I cannot propose a fix if you don't help searching for the cause.

**Comment by biaohanli** [comment]
it worked.thanks.

**Comment by k86228** [comment]
hi, i have tried the all model on Neurify, but all results are segmentation fault
I also used smaller model and above instruction in the previous comments
the results are still segmentation fault
Can i ask how you solved it
thank you
